version: "3.3"
services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - 8000:8000
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8600:8600"
  subscriber:
    build: ./subscriber
    restart: unless-stopped
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cloud
    volumes:
      - db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
volumes:
  db:
    driver: local