version: "3.3"
services:
  # subscriber:
  #   build: ./subscriber
  #   restart: unless-stopped
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cloud
    volumes:
      - db:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    ports:
      - 3000:3000
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
volumes:
  db:
    driver: local